# Population: Sexes by age in Ireland

## Part 1: Differences between sexes by age in Ireland

- Weighted mean age (by sex)

- The difference between the sexes by age - This part does not need to look at the regions.

ie You can take the notebook I used in the lectures and substitute the sexes for the regions.

In [5]:
# Import necessary libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import requests

print("Libraries imported successfully!")

Libraries imported successfully!

In [12]:
# URL of the dataset
url = "https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FY006A/CSV/1.0/en"

# Read the CSV file from the URL
data = pd.read_csv(url)

display (data.head())
display (data.tail())

,STATISTIC,Statistic Label,TLIST(A1),CensusYear,C02199V02655,Sex,C02076V03371,Single Year of Age,C03789V04537,Administrative Counties,UNIT,VALUE
0,FY006AC01,Population,2022,2022,-,Both sexes,-,All ages,IE0,Ireland,Number,5149139
1,FY006AC01,Population,2022,2022,-,Both sexes,-,All ages,2ae19629-1492-13a3-e055-000000000001,Carlow County Council,Number,61968
2,FY006AC01,Population,2022,2022,-,Both sexes,-,All ages,2ae19629-1433-13a3-e055-000000000001,Dublin City Council,Number,592713
3,FY006AC01,Population,2022,2022,-,Both sexes,-,All ages,2ae19629-149f-13a3-e055-000000000001,Dún Laoghaire Rathdown County Council,Number,233860
4,FY006AC01,Population,2022,2022,-,Both sexes,-,All ages,2ae19629-14a0-13a3-e055-000000000001,Fingal County Council,Number,330506

,STATISTIC,Statistic Label,TLIST(A1),CensusYear,C02199V02655,Sex,C02076V03371,Single Year of Age,C03789V04537,Administrative Counties,UNIT,VALUE
9787,FY006AC01,Population,2022,2022,2,Female,650,100 years and over,2ae19629-1497-13a3-e055-000000000001,Roscommon County Council,Number,7
9788,FY006AC01,Population,2022,2022,2,Female,650,100 years and over,2ae19629-1498-13a3-e055-000000000001,Sligo County Council,Number,9
9789,FY006AC01,Population,2022,2022,2,Female,650,100 years and over,2ae19629-149d-13a3-e055-000000000001,Cavan County Council,Number,12
9790,FY006AC01,Population,2022,2022,2,Female,650,100 years and over,2ae19629-14a4-13a3-e055-000000000001,Donegal County Council,Number,31
9791,FY006AC01,Population,2022,2022,2,Female,650,100 years and over,2ae19629-1495-13a3-e055-000000000001,Monaghan County Council,Number,7

# Part 2 - Make a variable that stores an age (say 35).

Write that code that would group the people within 5 years of that age together, into one age group 

Calculate the population difference between the sexes in that age group.

# Part 3 - Biggest population difference between the sexes in that age group